import { defineStore } from 'pinia'
import IconRain from '@/components/icons/IconRain.vue'
import IconCloudy from '@/components/icons/IconCloudy.vue'
import IconSun from '@/components/icons/IconSun.vue'
import IconWind from '@/components/icons/IconWind.vue'
import type { City } from '@/types/CitiesTypes'
type StateTypes = {
  city: City,
  cities: City[]
}
export const useCityStore = defineStore('city', {

  state: <StateTypes>() => ({
    city: {
      id: 1,
      name: 'Краснодар',
    },
    cities: [
      {
        name: 'Краснодар',
        id: 1,
        humidity: 75,
        icon: IconSun,
        temper: 29,
        speed: 1.3,
        condition: 'Солнечно',
        weekWeather: [
          { name: 'Понедельник', id: 1, icon: IconCloudy, temper: 28 },
          { name: 'Вторник', id: 2, icon: IconSun, temper: 34 },
          { name: 'Среда', id: 3, icon: IconWind, temper: 27 },
          { name: 'Четверг', id: 4, icon: IconRain, temper: 28 },
          { name: 'Пятница', id: 5, icon: IconCloudy, temper: 31 },
          { name: 'Суббота', id: 6, icon: IconSun, temper: 32 },
          { name: 'Воскресенье', id: 7, icon: IconRain, temper: 26 },
        ],
        hourWeather: [
          {
            time: '00:00',
            dayPeriod: 'Ночь',
            temper: 34,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '03:00',
            dayPeriod: 'Ночь',
            temper: 34,
            icon: IconSun,
            speed: 1,
            humidity: 85,
            condition: 'Солнечно',
          },
          {
            time: '06:00',
            dayPeriod: 'Утро',
            temper: 34,
            icon: IconWind,
            speed: 1,
            humidity: 85,
            condition: 'Ветренно',
          },
          {
            time: '09:00',
            dayPeriod: 'Утро',
            temper: '34',
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '12:00',
            dayPeriod: 'День',
            temper: 34,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '15:00',
            dayPeriod: 'День',
            temper: 34,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '18:00',
            dayPeriod: 'Вечер',
            temper: 34,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '21:00',
            dayPeriod: 'Вечер',
            temper: 34,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
        ],
      },
      {
        name: 'Москва',
        id: 2,
        humidity: 80,
        icon: IconRain,
        temper: 18,
        speed: 1.1,
        condition: 'Дождливо',
        weekWeather: [
          { name: 'Понедельник', id: 1, icon: IconRain, temper: 17 },
          { name: 'Вторник', id: 2, icon: IconCloudy, temper: 19 },
          { name: 'Среда', id: 3, icon: IconCloudy, temper: 20 },
          { name: 'Четверг', id: 4, icon: IconRain, temper: 16 },
          { name: 'Пятница', id: 5, icon: IconSun, temper: 22 },
          { name: 'Суббота', id: 6, icon: IconCloudy, temper: 18 },
          { name: 'Воскресенье', id: 7, icon: IconRain, temper: 15 },
        ],
        hourWeather: [
          {
            time: '00:00',
            dayPeriod: 'Ночь',
            temper: 23,
            icon: IconWind,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '03:00',
            dayPeriod: 'Ночь',
            temper: 26,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Солнечно',
          },
          {
            time: '06:00',
            dayPeriod: 'Утро',
            temper: 28,
            icon: IconSun,
            speed: 1,
            humidity: 85,
            condition: 'Ветренно',
          },
          {
            time: '09:00',
            dayPeriod: 'Утро',
            temper: 30,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '12:00',
            dayPeriod: 'День',
            temper: 32,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '15:00',
            dayPeriod: 'День',
            temper: 34,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '18:00',
            dayPeriod: 'Вечер',
            temper: 31,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '21:00',
            dayPeriod: 'Вечер',
            temper: 30,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
        ],
      },
      {
        name: 'Санкт-Петербург',
        id: 3,
        humidity: 90,
        temper: 15,
        icon: IconRain,
        speed: 1.15,
        condition: 'Дождливо',
        weekWeather: [
          { name: 'Понедельник', id: 1, icon: IconCloudy, temper: 14 },
          { name: 'Вторник', id: 2, icon: IconCloudy, temper: 16 },
          { name: 'Среда', id: 3, icon: IconRain, temper: 13 },
          { name: 'Четверг', id: 4, icon: IconCloudy, temper: 15 },
          { name: 'Пятница', id: 5, icon: IconCloudy, temper: 17 },
          { name: 'Суббота', id: 6, icon: IconWind, temper: 12 },
          { name: 'Воскресенье', id: 7, icon: IconCloudy, temper: 14 },
        ],
        hourWeather: [
          {
            time: '00:00',
            dayPeriod: 'Ночь',
            temper: 21,
            icon: IconWind,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '03:00',
            dayPeriod: 'Ночь',
            temper: 22,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Солнечно',
          },
          {
            time: '06:00',
            dayPeriod: 'Утро',
            temper: 25,
            icon: IconSun,
            speed: 1,
            humidity: 85,
            condition: 'Ветренно',
          },
          {
            time: '09:00',
            dayPeriod: 'Утро',
            temper: 27,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '12:00',
            dayPeriod: 'День',
            temper: 29,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '15:00',
            dayPeriod: 'День',
            temper: 32,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '18:00',
            dayPeriod: 'Вечер',
            temper: 31,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '21:00',
            dayPeriod: 'Вечер',
            temper: 29,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
        ],
      },
      {
        name: 'Екатеринбург',
        id: 4,
        humidity: 70,
        temper: 22,
        icon: IconCloudy,
        speed: 1.05,
        condition: 'Облачно',
        weekWeather: [
          { name: 'Понедельник', id: 1, icon: IconSun, temper: 20 },
          { name: 'Вторник', id: 2, icon: IconSun, temper: 24 },
          { name: 'Среда', id: 3, icon: IconCloudy, temper: 21 },
          { name: 'Четверг', id: 4, icon: IconSun, temper: 23 },
          { name: 'Пятница', id: 5, icon: IconSun, temper: 25 },
          { name: 'Суббота', id: 6, icon: IconCloudy, temper: 22 },
          { name: 'Воскресенье', id: 7, icon: IconSun, temper: 26 },
        ],
        hourWeather: [
          {
            time: '00:00',
            dayPeriod: 'Ночь',
            temper: 21,
            icon: IconWind,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '03:00',
            dayPeriod: 'Ночь',
            temper: 22,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Солнечно',
          },
          {
            time: '06:00',
            dayPeriod: 'Утро',
            temper: 25,
            icon: IconSun,
            speed: 1,
            humidity: 85,
            condition: 'Ветренно',
          },
          {
            time: '09:00',
            dayPeriod: 'Утро',
            temper: 27,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '12:00',
            dayPeriod: 'День',
            temper: 29,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '15:00',
            dayPeriod: 'День',
            temper: 32,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '18:00',
            dayPeriod: 'Вечер',
            temper: 31,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '21:00',
            dayPeriod: 'Вечер',
            temper: 29,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
        ],
      },
      {
        name: 'Новосибирск',
        id: 5,
        humidity: 65,
        temper: 25,
        icon: IconWind,
        speed: 1.27,
        condition: 'Ветренно',
        weekWeather: [
          { name: 'Понедельник', id: 1, icon: IconSun, temper: 23 },
          { name: 'Вторник', id: 2, icon: IconSun, temper: 26 },
          { name: 'Среда', id: 3, icon: IconSun, temper: 27 },
          { name: 'Четверг', id: 4, icon: IconCloudy, temper: 24 },
          { name: 'Пятница', id: 5, icon: IconSun, temper: 28 },
          { name: 'Суббота', id: 6, icon: IconSun, temper: 29 },
          { name: 'Воскресенье', id: 7, icon: IconCloudy, temper: 25 },
        ],
        hourWeather: [
          {
            time: '00:00',
            dayPeriod: 'Ночь',
            temper: 23,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '03:00',
            dayPeriod: 'Ночь',
            temper: 26,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Солнечно',
          },
          {
            time: '06:00',
            dayPeriod: 'Утро',
            temper: 28,
            icon: IconSun,
            speed: 1,
            humidity: 85,
            condition: 'Ветренно',
          },
          {
            time: '09:00',
            dayPeriod: 'Утро',
            temper: 30,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '12:00',
            dayPeriod: 'День',
            temper: 32,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '15:00',
            dayPeriod: 'День',
            temper: 34,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '18:00',
            dayPeriod: 'Вечер',
            temper: 31,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '21:00',
            dayPeriod: 'Вечер',
            temper: 30,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
        ],
      },
      {
        name: 'Сочи',
        id: 6,
        humidity: 85,
        temper: 32,
        speed: 1.17,
        icon: IconSun,
        condition: 'Солнечно',
        weekWeather: [
          { name: 'Понедельник', id: 1, icon: IconSun, temper: 30 },
          { name: 'Вторник', id: 2, icon: IconSun, temper: 33 },
          { name: 'Среда', id: 3, icon: IconSun, temper: 34 },
          { name: 'Четверг', id: 4, icon: IconRain, temper: 31 },
          { name: 'Пятница', id: 5, icon: IconSun, temper: 35 },
          { name: 'Суббота', id: 6, icon: IconSun, temper: 36 },
          { name: 'Воскресенье', id: 7, icon: IconCloudy, temper: 32 },
        ],
        hourWeather: [
          {
            time: '00:00',
            dayPeriod: 'Ночь',
            temper: 23,
            icon: IconWind,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '03:00',
            dayPeriod: 'Ночь',
            temper: 26,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Солнечно',
          },
          {
            time: '06:00',
            dayPeriod: 'Утро',
            temper: 28,
            icon: IconSun,
            speed: 1,
            humidity: 85,
            condition: 'Ветренно',
          },
          {
            time: '09:00',
            dayPeriod: 'Утро',
            temper: 30,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '12:00',
            dayPeriod: 'День',
            temper: 32,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '15:00',
            dayPeriod: 'День',
            temper: 34,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
          {
            time: '18:00',
            dayPeriod: 'Вечер',
            temper: 31,
            icon: IconCloudy,
            speed: 1,
            humidity: 85,
            condition: 'Дождливо',
          },
          {
            time: '21:00',
            dayPeriod: 'Вечер',
            temper: 30,
            icon: IconRain,
            speed: 1,
            humidity: 85,
            condition: 'Облачно',
          },
        ],
      },
    ],
  }),
  actions: {
    setCity(city: City) {
      this.city = city
    },
  },
})
